### ISSUE TITLE
Add full-screen loading modal after user hit "Save/Submit" form

### ISSUE THREAD

**Issue by sovesove** [MPH-Bali/green-village-project#108]
See: https://zpl.io/amBmjOK

The loader animation choice is up to devs. Just keep the size aligned to the design. (needs to be visible and high contrast with the background).

**Comment by nicksarafa** [comment]
NOOOOOOOOOOOOOOOOOOOOOOOOOO

**Comment by nicksarafa** [comment]
WHYYYYYYYYY

**Comment by nicksarafa** [comment]
FUCK MODALS

**Comment by nicksarafa** [comment]
MODALS ARE THE BANE OF UX EXISTENCE

**Comment by nicksarafa** [comment]
can we use something that isn't a full screen modal? how about a button with a loading indicator?

**Comment by nicksarafa** [comment]
or how about anything that isn't a full screen modal?

**Comment by nicksarafa** [comment]
i think this is one solution of many potential solutions for preventing the user from clicking around the screen when an action is taking place

**Comment by sovesove** [comment]
Let's not calling modal, let's call it full-screen loading feedback. :)
The loader on the buttons was present in the test and wasn't a good enough feedback for the user.
This is a overlay that will appear after a user action, so it is fair to assume that the user will expect something to happen.
We decided as a team that was the quickest solution, let's test it and see how it works!

**Comment by roma219** [comment]
We can have something like this : https://chryb.github.io/vueup/ , what do you guys think?

**Comment by sovesove** [comment]
Looks good to me. 
@JollyBrackets was talking to me about also other solutions (specifically for the "add material") using a sort of popup for a sort of in-page editing + animation on intro when the data get inserted in the table. 
Need to see how that would work. 
We just need a **clear** feedback to give the user after they submit a form, the loading on a button wasn't visible enough and the table was updating after few seconds (too slow for a success/fail feedback).

**Comment by roma219** [comment]
@sovesove I made a toast message on every successful operation (it pops up in the bottom of the screen), its it the dev branch

**Comment by nicksarafa** [comment]
we implemented toasts per @JollyBrackets suggestions. RIP MODALs

**Comment by nicksarafa** [comment]
#147

**Comment by sovesove** [comment]
I'll take the time to explain again the rationale behind this issue:

The reason why this issue was opened was to solve a problem observed at the facility.
**Description**
The user hit the Save button, the call to the server took too long to respond (prob due to poor connectivity), the loading indicator on the button wasn't visible enough due to size and light (the laptop was on the sunlight). The user then tried to tap somewhere else on the page to make something happening, not sure the webapp was actually working.
**Issue**
The user looked unsure about what was happening, didn't know what to expect and didn't know what to do. Likely ending up inserting duplicated data or interrupting the call to be submitted.
**Proposed solution**
A **loading** (not a "success" notification, although that helps in addition) fullscreen overlay/lightbox with an indicator (either graphical or textual, or better both) showing a loading status to explain the user what is happening and avoid him taking wrong actions.
**Action taken**
Add the loading overlay.
_A team of 4 (Andrea, Annika, Eli and Nick) discussed the solution and 3 votes were positive with going forward with the solution proposed by the design team, 1 vote was not in favour._


I feel there might have been some misunderstanding due to terminologies, so here's some definitions:

NNG seems also to be not too clear about definition and distinction between _modal_, _overlay_ and _lightbox_. But the main difference is that a _modal_ requires interaction, whereas _overlay_ and _lightbox_ are just elements on top of the page content (that cover the whole content, with or without interaction I guess depends if there's a modal on top of the overlay). 

> "Modal dialogs interrupt users and demand an action. **They are appropriate when user’s attention needs to be directed toward important information**."
Source: https://www.nngroup.com/articles/modal-nonmodal-dialog/

> "Definition: A modal dialog is a dialog that appears on top of the main content and moves the system into a special mode **requiring user interaction**. This dialog disables the main content until the user explicitly interacts with the modal dialog."
Source: https://www.nngroup.com/articles/modal-nonmodal-dialog/

> "Definition: An overlay refers to a content box that is displayed on top of another page. The overlay box is usually noticeably smaller than the underlying page. Often the rest of the background page is obscured, leading to the use of the term ‘lightbox’ to describe this visual effect of heightened focus on the overlay content."
Source: https://www.nngroup.com/articles/overuse-of-overlays/


The current solution, although solving the problem of giving the user feedback about the fact that the action taken was successful, still fails in few points:

- do not give feedback to the user when the action fail. There's no 'action failed' toast message neither 'timeout' message
- do not satisfy the first of the _10 Usability Heuristics for User Interface Design_  (since the current loader is not visible enough on the described scenario)
> **Visibility of system status**
> The system should always keep users informed about what is going on, through appropriate feedback within reasonable time.
Source: https://www.nngroup.com/articles/ten-usability-heuristics/
- discard what the team together agreed on

RIP MODALs especially those badly designed or built. LONG LIFE clear loading feedback.
