### ISSUE TITLE
Updated navigation

### ISSUE THREAD

**Issue by sovesove** [MPH-Bali/green-village-project#113]
Design on the way.

We will remove the bottom navigation, to give more space to the content.
The buttons will be moved into the Menu screen, accessible from the top-right link.

Zeplin: https://zpl.io/2jlzYN6

**Comment by youaresofunny** [comment]
https://github.com/MPH-Bali/green-village-project/pull/144

Just the template for new menu (for whom will take this issue)

**Comment by nicksarafa** [comment]
👍 thanks @youaresofunny @sovesove
