### ISSUE TITLE
Create Admin/Settings Page (optional)

### ISSUE THREAD

**Issue by JollyBrackets** [MPH-Bali/green-village-project#15]
The instance data / settings can be stored in the firebase realtime DB for simplicity.
To edit/change them we can use a single page with form fields for all props.

Sample of the setting data:

```javascript
var settings = {
  name: 'Facility 1',
  village: 'Canggu',
  importantVillageGuy: {
    id: 'Tu4SFfDhBUgAwGsvfopc',
    name: 'Guys Name'
  },
  houseTypes: [ //needed?
    { name: 'Villa', collectionFee: 20000 },
    { name: 'Local House', collectionFee: 1000 },
    { name: 'Business', collectionFee: 2500 }
  ],
  materials: [
    { name: 'Material 1', pricePerKilo: 2000 },
    { name: 'Material 2', pricePerKilo: 3000 }
    //...
  ],
  trucks: [
    { name: 'Truck 1', plate: 'ABC123', model: 'Toyota Trucki' },
    { name: 'Truck 2', plate: 'DEF456', model: 'Toyota Trucki' }
  ],
  banjars: [
    {
      name: 'Banjar Name',
      pickupTimes: {
        mon: '6am-2pm',
        tue: '6am-2pm'
        //...
      }
    }
  ]
}

```

- [ ] Create new top-level route **/admin**
- [ ] Add inputs and tables (inline edit) for all the props
- [ ] Add security rule (read if user.role.manager, write: if user.role.admin)

**Comment by nicksarafa** [comment]
we're using firebase admin dashboard for the time being. this issue won't be picked up until we have multiple deployments across different banjars
