### ISSUE TITLE
<Daily Log History> Logo is not clickable

### ISSUE THREAD

**Issue by annigoesintochicago** [MPH-Bali/green-village-project#158]
Logo in header doesn't lead anywhere

<img width="1002" alt="grafik" src="https://user-images.githubusercontent.com/37762492/37884688-7ff67d40-30b1-11e8-92aa-60c629ceb8d5.png">

**Comment by JollyBrackets** [comment]
@annigoesintochicago It is now. Should we keep the current behaviour (switch between public and manager view) or do something different?

**Comment by nicksarafa** [comment]
@JollyBrackets keep swtiching between views until we clean up routing
