### ISSUE TITLE
<Delivery form> Select more than one Banjar not possible

### ISSUE THREAD

**Issue by annigoesintochicago** [MPH-Bali/green-village-project#159]
It says: "Select one or **more** Banjar" in the dropdown, but you can actually just select one.

<img width="514" alt="grafik" src="https://user-images.githubusercontent.com/37762492/37884728-b0d6f25a-30b1-11e8-9954-85569be24b85.png">

**Comment by nicksarafa** [comment]
@annigoesintochicago this is delibrate. there is a one to one relationship between the drop off and the banjar
