### ISSUE TITLE
<Delivery Entry> Entries are made for every day

### ISSUE THREAD

**Issue by annigoesintochicago** [MPH-Bali/green-village-project#161]
When I go back to another day, my daily entry made is shown there aswell.

<img width="886" alt="grafik" src="https://user-images.githubusercontent.com/37762492/37884875-6cc0b938-30b2-11e8-9b10-bbf89f84124b.png">

<img width="884" alt="grafik" src="https://user-images.githubusercontent.com/37762492/37884880-736ac21a-30b2-11e8-8926-77dee6b98a96.png">

**Comment by JollyBrackets** [comment]
@annigoesintochicago this should be fixed. Can you please check and close if it works.

Note: Currently it's not possible to create entries for the past. Is this intended?

**Comment by nicksarafa** [comment]
this is fixed 👍
