### ISSUE TITLE
<Workers hours> "edit button" doesn't work

### ISSUE THREAD

**Issue by annigoesintochicago** [MPH-Bali/green-village-project#164]
• When clicking on "edit button" blank page appears (tested in firefox 59.0.1 (64-Bit))

**Comment by piggydoughnut** [comment]
Please test in Chrome, that is supported for sure. Since this is now a Progressive Web App it will only be viewable in Chrome. :D cheerz

**Comment by annigoesintochicago** [comment]
You're right. I forgot about that :-)
