### ISSUE TITLE
Add phone auth

### ISSUE THREAD

**Issue by JollyBrackets** [MPH-Bali/green-village-project#17]
- [ ] Enable  Phone Auth on the project ([see how](https://firebase.google.com/docs/auth/web/phone-auth))
- [ ] Add **person** Collection to Firestore
- [ ] Add **Login** & **Confirmation** components
- [ ] Hide **Manager** components if no manager is looged in

**Comment by nicksarafa** [comment]
#127

**Comment by nicksarafa** [comment]
we should turn ` Hide Manager components if no manager is looged in` into a seperate issue
