### ISSUE TITLE
i18n

### ISSUE THREAD

**Issue by JollyBrackets** [MPH-Bali/green-village-project#18]
- [ ] Replace all Strings with `$t("VIEW.STRING")`
- [ ] Have someone translate all strings
- [ ] Add a language picker

**Comment by nicksarafa** [comment]
@ejohnst2 you have the language picker init

**Comment by nicksarafa** [comment]
Yudis is translating strings, and i'm updating the views to corrleate with the correct strings

**Comment by nicksarafa** [comment]
#61
