### ISSUE TITLE
Direct URL is not working

### ISSUE THREAD

**Issue by sovesove** [MPH-Bali/green-village-project#181]
If I'm trying to open this page:
https://powerful-condition.surge.sh/manager/daily-log/2018-03-26
(or reloading the app while I am in this URL)

I get a 404

**Comment by JollyBrackets** [comment]
@sovesove @nicksarafa this happens only on surge, firebase works fine, [see](https://mph-bali.firebaseapp.com/manager/daily-log/2018-03-26). 

My recommendation would be to only deploy to firebase and create a second firebase project for the dev branch.

If you want to keep surge: make sure to redirect all requests to index.html. This would look something like this:
```

"rewrites": [
      {
        "source": "**",
        "destination": "/index.html"
      }
    ]
```

**Comment by nicksarafa** [comment]
surges are for janky test deployments. this issue isn't relevant good catch tho @sovesove
