### ISSUE TITLE
Add stock type needs to list all the subtypes

### ISSUE THREAD

**Issue by sovesove** [MPH-Bali/green-village-project#182]
![image](https://user-images.githubusercontent.com/940045/37889832-d4b477d4-3100-11e8-843e-100a47d53021.png)

Plastic, Paper, Metal all have a bunch of subtypes, @piggydoughnut and @mediashane knows 😄 
The type will never be "Plastic" only but "Plastic - {subtype}".
Same for Paper and Metal.
Compost has no subtypes.

**Comment by mediashane** [comment]
Working on it 🙂

**Comment by mediashane** [comment]
@sovesove Design question on how this should be presented. Do you imagine one long drop down of twenty types+sub-types ("Plastic - {subtype}"), or two drop downs of type and sub-type separated (see screenshot)? 

![subtypes](https://user-images.githubusercontent.com/14046192/37910609-89372a00-3140-11e8-8a94-1ac21d51a693.jpg)

**Comment by sovesove** [comment]
Go for the two dropdowns!
We will improve the dropdowns design later on tho.

——————

Andrea Soverini

twitter: @sovesove <https://twitter.com/sovesove>

**Comment by mediashane** [comment]
This issue will now be solved by combining the Type and Subtype dropdown menus into one and displaying the combination under a Type column in the Stock tables.

**Comment by mediashane** [comment]
After testing with combining Type and Subtypes together in the data model ("Plastic - {subtype}"), I've reverted to my previous belief that keeping them in two different drop downs is the better solution for now.

**Comment by nicksarafa** [comment]
@mediashane i agree with the seperation of the drop downs. keeps things more compartamentalized and easier to iteriate later

**Comment by nicksarafa** [comment]
marking as closed thanks @mediashane 👍
