### ISSUE TITLE
<community page> Header Design

### ISSUE THREAD

**Issue by annigoesintochicago** [MPH-Bali/green-village-project#190]
Header Design is not as it's supposed to be

![image](https://user-images.githubusercontent.com/37762492/37894118-6b2bbbce-30dd-11e8-8bd0-0fdc713a7d2d.png)

Should look like this:
![image](https://user-images.githubusercontent.com/37762492/37894129-76c6926a-30dd-11e8-9649-79b1a2dddaa8.png)

**Comment by nicksarafa** [comment]
fixed in #241
