### ISSUE TITLE
Security Rules & Validation

### ISSUE THREAD

**Issue by JollyBrackets** [MPH-Bali/green-village-project#20]
- [x] Settings (firebase realtime db)
- [x] Delivery
- [x] Person
- [x] WorkedHours
- [x] Stock
- [x] Expense
- [x] Sale
- [x] Fee
- [x] Banjar
- [x] Material
- [x] MaterialType
- [x] houseType

**Comment by piggydoughnut** [comment]
Validate that a user has only one role at the time.

**Comment by nicksarafa** [comment]
👍
