### ISSUE TITLE
Add stock table needs to show "Type" column

### ISSUE THREAD

**Issue by sovesove** [MPH-Bali/green-village-project#219]
https://mph-bali.firebaseapp.com/manager/stock

![image](https://user-images.githubusercontent.com/940045/38023784-c041c098-32b5-11e8-9452-7ed0511057c4.png)

**Comment by mediashane** [comment]
So even though the table is called Plastics there should still be a Type:
Plastics column header in the table? It's easy to do, I just wanted to make
sure we're not duplicating efforts.

**Comment by sovesove** [comment]
No, this is related to the other issue where we would have "subtype" but Type and Subtype can be displayed in the same column as:
Plastic - PTLE.

The goal is to display the subtype really, but how we can solve this depends on how you are implementing it I guess.

**Comment by mediashane** [comment]
I'd originally thought to separate the Type and Subtype drop-down menus out, but I see your logic here and will just combine them into one drop down. I'd originally wanted to split them up to keep the drop down menus shorter, but combining them makes it more simple for the user and for our data structure.

**Comment by mediashane** [comment]
So this was easy to implement on the Add Stock screen, but very difficult to manage on the Daily Log screen without the tables becoming messy and confusing. My temporary solution was to break out the Stock into different Daily Logs (so there is a Daily Log table for each stock type). Below is what the Stocks tables look like now on the Daily Log screen (Compost is collapsed, Plastics is expanded and showing Subtypes).

![subtypesdaily](https://user-images.githubusercontent.com/14046192/38073201-9929b090-335c-11e8-82f1-b5641764a343.jpg)

**Comment by sovesove** [comment]
Thanks Shane, looks like a good enough solution for the time being.
Another solution could have been to also show the Type in the table, although I understand is redundant. We will iterate to understand what's best.
👍

**Comment by nicksarafa** [comment]
thanks @mediashane marking this one as closed
