### ISSUE TITLE
How to run green-village-project locally on linux ubuntu

### ISSUE THREAD

**Issue by Mlondo** [MPH-Bali/green-village-project#246]
I'm Alex, I'm trying to run the green village project on Linux, however, I don't know the tool needed to run. 

Please if you can, please send a list of tool required. I want want to join the development team

**Comment by nicksarafa** [comment]
Hey! You will need [yarn](https://yarnpkg.com/en/docs/) installed locally to run the project.

```
$ cd green-village-project/public
$ yarn
$ yarn start
```

Let me know if that does the trick!

**Comment by Mlondo** [comment]
I run yarn, however, I'm getting the following message:
There are no scenarios; must have at least one.

**Comment by Mlondo** [comment]
Sorted thanks Nick
