### ISSUE TITLE
Core: Public Facing Homepage with Chart.js

### ISSUE THREAD

**Issue by ejohnst2** [MPH-Bali/green-village-project#26]
For the public facing interface, we'll use the Vue wrapper for Chart.js 

We can make simple, reusable graphs with multilple data sets, just need to add a function or two to have it auto-refresh the data being passed to it. 

Library for Wrapper: https://github.com/apertureless/vue-chartjs
Documentation for Chartjs: http://www.chartjs.org/docs/latest/getting-started/usage.html

**Comment by nicksarafa** [comment]
feature was introduced with #142

**Comment by nicksarafa** [comment]
👍
