### ISSUE TITLE
05.0 Check-in workers

### ISSUE THREAD

**Issue by WillisDrynkn** [MPH-Bali/green-village-project#50]
https://trello.com/c/uF5Lo201/15-050-check-in-workers

**Comment by sovesove** [comment]
Functionality simplified to only have time in-out (once, not morning+afternoon).
Drop downs will show hours in the format 08:00 from 01:00 to 12:00
A toggle AM/PM will be displayed next to the time picker.

see new design: https://zpl.io/2jl31Kq

**Comment by youaresofunny** [comment]
Move into https://github.com/MPH-Bali/green-village-project/issues/51
