### ISSUE TITLE
05.0a Check-in workers

### ISSUE THREAD

**Issue by WillisDrynkn** [MPH-Bali/green-village-project#51]
https://trello.com/c/WWdU8vaY/43-050a-check-in-workers

**Comment by sovesove** [comment]
Functionality simplified to only have time in-out (once, not morning+afternoon).
**Option1**
The time picker will show the clock UI selecting only the hours.
Minutes will be defaulted to :00
The "Save" button need to be full green, currently is not visible.

**Option2**
If it's not possible to remove the minutes from the clock picker.
The time picker will be a drop down and will only show fixed hours **from 6:00am to 10:00pm**

**Comment by youaresofunny** [comment]
https://github.com/MPH-Bali/green-village-project/pull/79
