### ISSUE TITLE
09.1a Warning

### ISSUE THREAD

**Issue by WillisDrynkn** [MPH-Bali/green-village-project#56]
https://trello.com/c/z3b2RAAz/36-091a-warning

**Comment by sovesove** [comment]
Every form should have a modal confirmation that ask the user to confirm if they want to loose their changes when user *refresh the page* or hit *cancel*

**Comment by nicksarafa** [comment]
@sovesove has this been implemented yet?

**Comment by sovesove** [comment]
No, but forms are caching input results even after the users navigates to another page, so data is not lost accidentally. So that's fix the problem.
