### ISSUE TITLE
NavigationHeader component (back, date, forward, action)

### ISSUE THREAD

**Issue by youaresofunny** [MPH-Bali/green-village-project#65]
![selection_207](https://user-images.githubusercontent.com/1954900/37860887-f2ebecd6-2f3f-11e8-9c6f-e57e053be0d4.png)
![selection_208](https://user-images.githubusercontent.com/1954900/37860888-050bcc1a-2f40-11e8-9793-16e56f37e562.png)
![selection_209](https://user-images.githubusercontent.com/1954900/37860894-158e25c4-2f40-11e8-87c9-efd6187f75ce.png)

3 slots (left, middle, right)
Default actions:
left - back
middle - date (can also display date from prop)

**Comment by youaresofunny** [comment]
@sovesove can we unify arrors ( the second screenshot ones got no text and diferent style)?

**Comment by sovesove** [comment]
The second screenshot is from a screen where arrows should move to prev/next day. (possible to move them near the calendar, or just have a date picker in the date field.

**Comment by youaresofunny** [comment]
https://github.com/MPH-Bali/green-village-project/pull/73
