### ISSUE TITLE
Organic/Anaorganic data in Delivery table need to go.

### ISSUE THREAD

**Issue by sovesove** [MPH-Bali/green-village-project#81]
![image](https://user-images.githubusercontent.com/940045/37870556-ae283b00-300b-11e8-8c7a-b2e7c2ffc09d.png)

In the Delivery table+form we have data for Organic/Anaorganic, this is not supposed to be there.
see: https://zpl.io/2po91Ll

We already have this data table+form in the Material section.
see: https://zpl.io/bP4eJ9A

**Comment by JollyBrackets** [comment]
Tested, works
