### ISSUE TITLE
Add Material - Banjar is optional

### ISSUE THREAD

**Issue by sovesove** [MPH-Bali/green-village-project#86]
![image](https://user-images.githubusercontent.com/940045/37870819-71cdd20e-3011-11e8-9563-d12cd75014cc.png)

The user needs to be able to select no banjar. 
Context: currently they don't have this information (so default to "empty"), but in the future they want to track this.

**Comment by youaresofunny** [comment]
https://github.com/MPH-Bali/green-village-project/pull/131

**Comment by nicksarafa** [comment]
👍
