### ISSUE TITLE
Time format needs to be 12h am/pm across the whole webapp

### ISSUE THREAD

**Issue by sovesove** [MPH-Bali/green-village-project#91]

**Comment by nicksarafa** [comment]
@sovesove can you please point out where the time is __not__ being set by 12 am/pm?

we'll probably want to build a global component for the 12 hour am/pm time picker to support this feature through the app if its used more than twice

**Comment by sovesove** [comment]
I think everything has been updated by now. Probably was only for the workers hour table which has been updated after implementing the new time picker with AM/PM.
